### PR TITLE
Rails and docker

### PR DESCRIPTION
**Pull request by rivernate**
test plan:
it should run in docker and locally

### CODE REVIEW

**Comment by westonkd** [comment]
Looks like the issue persists even when I rollback to bbd766ede08100e078ecfec65e3ea91765be6ff0

**Comment by rivernate** [comment]
do you get an error when you run: `docker compose exec web bundle exec rake db:create`

**Comment by westonkd** [comment]
Looks like the errors were on my part. After deleting volumes and trying again everything worked great

**Comment by westonkd** [comment]
I closed my previous pull request will all the tool registration functionality. I'm going to rebase it on top of this. It's going to be easier just to copy the needed files and in a new branch I think.

**Pull request merged**
